development:
  adapter: postgresql
  encoding: unicode
  database: audarme
  username: postgres
  password: RedHawks2013

test:
  adapter: postgresql
  encoding: unicode
  database: audarme
  pool: 5
  username: postgres
  password: RedHawks2013
