development:
  adapter: postgresql
  encoding: unicode
  database: audarme
  username: postgres
  password: root
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: audarme
  pool: 5
  username: postgres
  password: root
  host: localhost
